### ISSUE TITLE
Review comments

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-module-interspace-mastercuev7#1]
Nothing here is worth blocking its inclusion in the builds, just some suggestions.

Having variables scoped outside the class is bad practise but does work https://github.com/bitfocus/companion-module-interspace-mastercuev7/blob/86a844e2bac5ae19180a5a219ca954c91a0d2bcb/main.js#L9-L18
In 2.4 and older this would have been a bug as it would be shared by all instances of your module. In 3.0 this wont be a bug, but things like this could be set as properties on the class instead.

https://github.com/bitfocus/companion-module-interspace-mastercuev7/blob/86a844e2bac5ae19180a5a219ca954c91a0d2bcb/main.js#L183-L186
When doing multiple `checkFeedbacks` in a row, it is better to do it as multiple arguments instead of multiple calls.
```
this.checkFeedbacks('output_channel_feedback', 'next_feedback', 'back_feedback', 'blackout_feedback');
```
Its a performance thing, instead of making companion iterate through the array of feedbacks 4 times, it can do 1 iteration to find them all

https://github.com/bitfocus/companion-module-interspace-mastercuev7/blob/86a844e2bac5ae19180a5a219ca954c91a0d2bcb/feedbacks.js#L11
The `defaultStyle` property doesnt do anything for 'advanced' feedbacks.

I would recommend seeing if you could convert any of those feedbacks to be of the 'boolean' type. The great thing about boolean feedbacks is that while the module dev suggests the style to use, the user can then customise that

**Comment by Luuccc** [comment]
Thank you very much for your feedback!

I've addressed the mentioned bad scoping practice, the unnecessary use of `defaultStyle` properties, as well as reducing `checkFeedbacks` to a single call.

I've also looked into the possibility of migrating some of the feedbacks to boolean types. However, with the current method of styling I'm using, it may not work.

Although, I might create some extra/alternative boolean feedback methods in future to allow for more styling options. 

Thanks again!
